guest: false
database:
    client: sqlite3
    connection:
        filename: tmp/db.sqlite
listen:
    host: localhost
    port: 8000
redis:
    host: localhost
session:
    resave: true
    saveUninitialized: true
    store: database
types:
    sw2_character_ja: ソード・ワールド2.0/キャラクター
